export const USER_SIGN_IN = "USER_SIGN_IN"
export const USER_SIGN_UP = "USER_SIGN_UP"
export const USER_SIGN_OUT = "USER_SIGN_OUT"
export const GOOGLE = "_GOOGLE"
export const BASE_URL = "https://guest-board-api.herokuapp.com/api/v1"
export const START = "_START"
export const SUCCESS = "_SUCCESS"
export const FAIL = "_FAIL"
